---
ID: "89dcd02f-e87b-4820-a19c-206e586f91fb"
Parent: "446b05ee-9442-455a-9684-038be070a2ad"
Template: "446b05ee-9442-455a-9684-038be070a2ad"
Path: /sitecore/templates/Algolia/Datasources/Hits/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160327T224529
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
    - ID: "f3cd0a9f-c4b4-4f21-af3f-116e59a6b23e"
      Hint: Hits Per Page
      Value: 10
