---
ID: "c582afa9-436f-43f1-9e24-1fcc9a2ad18d"
Parent: "1488fd93-53a9-42ca-afb4-5a2bb52cae29"
Template: "1488fd93-53a9-42ca-afb4-5a2bb52cae29"
Path: /sitecore/templates/Algolia/Datasources/Pagination/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160416T184435
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
    - ID: "e3486a70-4d10-4452-b909-142e3a256dab"
      Hint: Max Pages
      Value: 100
    - ID: "e4ce969a-55d9-4893-a3e5-5bfe8951d585"
      Hint: Scroll To
      Value: body
