---
ID: "847c0fdc-d429-47fb-b100-ff0b447903b9"
Parent: "44b1e917-cace-488f-8152-7a9cbe212f08"
Template: "44b1e917-cace-488f-8152-7a9cbe212f08"
Path: /sitecore/templates/Algolia/Base/Key Value/__Standard Values
DB: master
SharedFields:
- ID: "8d53ed75-24d7-4440-b477-f5f05c747f1c"
  Hint: Key
  Value: $name
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160412T225300
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
    - ID: "dd87f403-428b-4a8c-80af-3beb1f00d620"
      Hint: Value
      Value: $name
